from typing import Optional

from pydantic import BaseModel


class CharacterCreateRequest(BaseModel):
    name: str
    persona: dict  # {age, heritage, appearance, body_type, style, color_palette, location, personality}
    provider: str = "openai"  # openai | gemini
    reference_count: int = 1
    # When set, the new base image is generated by referencing the anchor
    # character's existing images (its base + saved references). This is the
    # "다시만들기" / remake flow — same persona, fresh shot, identity preserved.
    anchor_character_id: Optional[str] = None


class CharacterResponse(BaseModel):
    id: str
    name: str
    persona: dict
    base_image_id: str
    is_active: bool
    created_at: str
    updated_at: str
    references: list[dict]  # [{id, role, image_id}]

    class Config:
        from_attributes = True
